// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestZL.DAL;

namespace TestZL.Migrations
{
    [DbContext(typeof(TestZLContext))]
    partial class TestZLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestZL.Models.Database.LoadItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCaseSensitivity")
                        .HasColumnType("bit");

                    b.Property<bool>("IsContainsCyrillic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsContainsDigits")
                        .HasColumnType("bit");

                    b.Property<bool>("IsContainsLatin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsContainsSpecialChars")
                        .HasColumnType("bit");

                    b.Property<string>("LocalPathToFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MarkupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MarkupId");

                    b.ToTable("LoadItems");
                });

            modelBuilder.Entity("TestZL.Models.Database.LocationMarkup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Syn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LocationMarkups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9139e3a1-99bb-4a41-b780-64351e4dbd03"),
                            Name = "отсутствует",
                            Syn = "None"
                        },
                        new
                        {
                            Id = new Guid("2ce9b57e-0cca-4814-afcb-a3bb1315c8b7"),
                            Name = "в именах файлов",
                            Syn = "InFileName"
                        },
                        new
                        {
                            Id = new Guid("7de3638f-a6b3-4cbd-9493-8cb2d632858e"),
                            Name = "в отдельном файле",
                            Syn = "InSeparateFile"
                        });
                });

            modelBuilder.Entity("TestZL.Models.Database.LoadItem", b =>
                {
                    b.HasOne("TestZL.Models.Database.LocationMarkup", "Markup")
                        .WithMany()
                        .HasForeignKey("MarkupId");
                });
#pragma warning restore 612, 618
        }
    }
}
